<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE tree [
<!ELEMENT tree (branch)+>
<!ELEMENT branch (node)+>
<!ELEMENT node (path_segment,parent_path_segment?,value?)>
<!ELEMENT path_segment (#PCDATA)>
<!ELEMENT parent_path_segment (#PCDATA)>
<!ELEMENT value (#PCDATA)>
]>
<tree>
<branch>

<node>
<path_segment>dp_20200709090613_hie006_imp1</path_segment>
<parent_path_segment></parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\basedon</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1</parent_path_segment>
<value>wizard_lib</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\commonprops</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\commonprops\commonprop2</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\commonprops</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\commonprops\commonprop2\must</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\commonprops\commonprop2</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\commonprops\commonprop2\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\commonprops\commonprop2</parent_path_segment>
<value>STUDY_DESCRIPTION</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\getereport</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\minimum_study_age</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1</parent_path_segment>
<value>PrevSameDescription</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\sortby</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\sortby\ascending</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\sortby</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\sortby\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\sortby</parent_path_segment>
<value>STUDY_DATE</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\sortby\studiesnumber</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata1\sortby</parent_path_segment>
<value>10</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\basedon</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2</parent_path_segment>
<value>wizard_lib</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2\must</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2</parent_path_segment>
<value>MODALITY</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2\value</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2</parent_path_segment>
<value>CT</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3\must</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3</parent_path_segment>
<value>TAMAR_STUDY_BODY_PART</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3\value</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3</parent_path_segment>
<value>CHEST</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\getereport</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\minimum_study_age</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2</parent_path_segment>
<value>PrevCT_CHEST</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\sortby</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\sortby\ascending</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\sortby</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\sortby\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\sortby</parent_path_segment>
<value>STUDY_DATE</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\sortby\studiesnumber</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata2\sortby</parent_path_segment>
<value>2</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata3</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata3\basedon</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata3</parent_path_segment>
<value>baseline_body_descr</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata3\getereport</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata3</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata3\minimum_study_age</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata3</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata3\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata\additionaldata3</parent_path_segment>
<value>baseline_body_descr</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\loadkeyimagesonly</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\additionaldata\use_compound_modality</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\additionaldata</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\changed_by_converter_11.1</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\dp_type</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1</parent_path_segment>
<value>Standard_DP</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\enable</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\groupingrules</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\conditions</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\conditions\condition1</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\conditions</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\conditions\condition1\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\conditions\condition1</parent_path_segment>
<value>MODALITY</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\conditions\condition1\value</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\conditions\condition1</parent_path_segment>
<value>CR,DR,DX</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\items</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\items\item1</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\items</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\items\item1\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\items\item1</parent_path_segment>
<value>STUDY_INSTANCE_UID</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\items\item1\type</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\items\item1</parent_path_segment>
<value>RestDistinct</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\items\item2</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\items</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\items\item2\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\items\item2</parent_path_segment>
<value>SERIES_NUMBER</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\items\item2\type</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\items\item2</parent_path_segment>
<value>RestDistinct</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\groupingrules\groupingrule1</parent_path_segment>
<value>For Chest  all in one</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\locked_for_edit</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1</parent_path_segment>
<value>CR Lungor Erik</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\ascending</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1</parent_path_segment>
<value>AllInOneGroup_CR0_PA</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value1</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value1\ascending</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value1</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value1\index</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value1</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value1\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value1</parent_path_segment>
<value>STUDY_INSTANCE_UID</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value1\sort</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value1</parent_path_segment>
<value>STUDY_DATE</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value1\valuetype</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value1</parent_path_segment>
<value>reference</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value2</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value2\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value2</parent_path_segment>
<value>Group_All_Images</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value2\value</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value2</parent_path_segment>
<value>True</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value2\valuetype</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup1\value2</parent_path_segment>
<value>GroupAttribute</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10</parent_path_segment>
<value>AllinonegroupCR9</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value1</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value1\ascending</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value1</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value1\index</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value1</parent_path_segment>
<value>9</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value1\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value1</parent_path_segment>
<value>STUDY_INSTANCE_UID</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value1\sort</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value1</parent_path_segment>
<value>STUDY_DATE</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value1\valuetype</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value1</parent_path_segment>
<value>reference</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value2</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value2\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value2</parent_path_segment>
<value>Group_All_Images</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value2\value</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value2</parent_path_segment>
<value>True</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value2\valuetype</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup10\value2</parent_path_segment>
<value>GroupAttribute</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11</parent_path_segment>
<value>AllinonegroupCR10</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value1</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value1\ascending</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value1</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value1\index</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value1</parent_path_segment>
<value>10</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value1\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value1</parent_path_segment>
<value>STUDY_INSTANCE_UID</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value1\sort</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value1</parent_path_segment>
<value>STUDY_DATE</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value1\valuetype</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value1</parent_path_segment>
<value>reference</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value2</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value2\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value2</parent_path_segment>
<value>Group_All_Images</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value2\value</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value2</parent_path_segment>
<value>True</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value2\valuetype</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup11\value2</parent_path_segment>
<value>GroupAttribute</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12</parent_path_segment>
<value>Allinonegroupfirst</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value1</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value1\ascending</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value1</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value1\index</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value1</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value1\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value1</parent_path_segment>
<value>STUDY_INSTANCE_UID</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value1\sort</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value1</parent_path_segment>
<value>STUDY_DATE</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value1\valuetype</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value1</parent_path_segment>
<value>reference</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value2</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value2\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value2</parent_path_segment>
<value>Group_All_Images</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value2\value</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value2</parent_path_segment>
<value>True</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value2\valuetype</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup12\value2</parent_path_segment>
<value>GroupAttribute</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13</parent_path_segment>
<value>AllinonegroupCR11</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value1</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value1\ascending</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value1</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value1\index</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value1</parent_path_segment>
<value>11</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value1\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value1</parent_path_segment>
<value>STUDY_INSTANCE_UID</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value1\sort</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value1</parent_path_segment>
<value>STUDY_DATE</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value1\valuetype</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value1</parent_path_segment>
<value>reference</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value2</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value2\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value2</parent_path_segment>
<value>Group_All_Images</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value2\value</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value2</parent_path_segment>
<value>True</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value2\valuetype</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup13\value2</parent_path_segment>
<value>GroupAttribute</value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup14</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup14\name</path_segment>
<parent_path_segment>dp_20200709090613_hie006_imp1\nominalgroups\nominalgroup14</parent_path_segment>
<value>c_frontal</value>