<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE tree [
<!ELEMENT tree (branch)+>
<!ELEMENT branch (node)+>
<!ELEMENT node (path_segment,parent_path_segment?,value?)>
<!ELEMENT path_segment (#PCDATA)>
<!ELEMENT parent_path_segment (#PCDATA)>
<!ELEMENT value (#PCDATA)>
]>
<tree>
<branch>

<node>
<path_segment>dp_20200708160719_hie006_imp1</path_segment>
<parent_path_segment></parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\basedon</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1</parent_path_segment>
<value>wizard_lib</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\commonprops</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\commonprops\commonprop2</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\commonprops</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\commonprops\commonprop2\must</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\commonprops\commonprop2</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\commonprops\commonprop2\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\commonprops\commonprop2</parent_path_segment>
<value>TAMAR_STUDY_BODY_PART</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\getereport</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\minimum_study_age</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1</parent_path_segment>
<value>PrevSameBodyPart</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\sortby</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\sortby\ascending</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\sortby</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\sortby\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\sortby</parent_path_segment>
<value>STUDY_DATE</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\sortby\studiesnumber</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata1\sortby</parent_path_segment>
<value>5</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\basedon</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2</parent_path_segment>
<value>wizard_lib</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2\must</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2</parent_path_segment>
<value>MODALITY</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2\value</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop2</parent_path_segment>
<value>CT</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3\must</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3</parent_path_segment>
<value>TAMAR_STUDY_BODY_PART</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3\value</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\differentprops\differentprop3</parent_path_segment>
<value>CHEST|ABDOMEN|BODY</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\getereport</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\minimum_study_age</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2</parent_path_segment>
<value>PrevCT_CHEST|ABDOMEN|BODY</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\sortby</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\sortby\ascending</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\sortby</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\sortby\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\sortby</parent_path_segment>
<value>STUDY_DATE</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\sortby\studiesnumber</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata\additionaldata2\sortby</parent_path_segment>
<value>6</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\loadkeyimagesonly</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\additionaldata\use_compound_modality</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\additionaldata</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\changed_by_converter_11.1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\dp_type</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1</parent_path_segment>
<value>Standard_DP</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\enable</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\conditions</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\conditions\condition1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\conditions</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\conditions\condition1\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\conditions\condition1</parent_path_segment>
<value>TAMAR_MISC_STRING_1</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\conditions\condition1\value</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\conditions\condition1</parent_path_segment>
<value>GE</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item1\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item1</parent_path_segment>
<value>STUDY_INSTANCE_UID</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item1\type</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item1</parent_path_segment>
<value>RestDistinct</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item2</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item2\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item2</parent_path_segment>
<value>IMAGE_TYPE</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item2\type</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item2</parent_path_segment>
<value>RestDistinct</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\buckets</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\buckets\bucket1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\buckets</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\buckets\bucket1\buckettype</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\buckets\bucket1</parent_path_segment>
<value>BucketTypeChars</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\buckets\bucket1\prefix_string</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\buckets\bucket1</parent_path_segment>
<value>CONTRAST</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\description</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\description\value1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\description</parent_path_segment>
<value>SERIES_NUMBER</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\description\value2</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\description</parent_path_segment>
<value>SERIES_DESCRIPTION</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\description\value3</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\description</parent_path_segment>
<value>TAMAR_IMAGE_ORIENTATION</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3</parent_path_segment>
<value>SERIES_NUMBER</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3\type</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item3</parent_path_segment>
<value>RestDistinct</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item4</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item4\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item4</parent_path_segment>
<value>ACQUISITION_TIME</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item4\type</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\items\item4</parent_path_segment>
<value>RestDistinct</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule1</parent_path_segment>
<value>For GE CT splitt series on acquisition time with Parsing24.</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule2</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule2\basedon</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule2</parent_path_segment>
<value>ct_basic</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule2\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule2</parent_path_segment>
<value>For CT</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule3</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule3\basedon</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule3</parent_path_segment>
<value>mr_basic</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule3\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule3</parent_path_segment>
<value>For MR</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule4</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule4\basedon</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule4</parent_path_segment>
<value>xa_mf</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule4\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule4</parent_path_segment>
<value>For XA</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\conditions</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\conditions\condition1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\conditions</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\conditions\condition1\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\conditions\condition1</parent_path_segment>
<value>SOP_CLASS_UID</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\conditions\condition1\value</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\conditions\condition1</parent_path_segment>
<value>1.2.840.10008.5.1.4.1.1.6.1</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items\item1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items\item1\description</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items\item1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items\item1\description\value1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items\item1\description</parent_path_segment>
<value>IMAGE_TIME</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items\item1\description\value2</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items\item1\description</parent_path_segment>
<value>SOP_CLASS_UID</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items\item1\description\value3</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items\item1\description</parent_path_segment>
<value>SERIES_NUMBER</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items\item1\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items\item1</parent_path_segment>
<value>STUDY_INSTANCE_UID</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items\item1\type</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\items\item1</parent_path_segment>
<value>RestDistinct</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule5</parent_path_segment>
<value>For US images</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\conditions</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\conditions\condition1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\conditions</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\conditions\condition1\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\conditions\condition1</parent_path_segment>
<value>MODALITY</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\conditions\condition1\value</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\conditions\condition1</parent_path_segment>
<value>US</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item1\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item1</parent_path_segment>
<value>STUDY_INSTANCE_UID</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item1\type</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item1</parent_path_segment>
<value>RestDistinct</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item2</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item2\description</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item2</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item2\description\value1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item2\description</parent_path_segment>
<value>IMAGE_TIME</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item2\description\value2</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item2\description</parent_path_segment>
<value>SOP_CLASS_UID</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item2\description\value3</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item2\description</parent_path_segment>
<value>SERIES_NUMBER</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item2\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item2</parent_path_segment>
<value>IMAGE_TIME</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item2\type</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\items\item2</parent_path_segment>
<value>RestDistinct</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\groupingrules\groupingrule6</parent_path_segment>
<value>For US multiframe</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\locked_for_edit</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1</parent_path_segment>
<value>DT thorax Erik</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\nominalgroups</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\nominalgroups\ascending</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\nominalgroups</parent_path_segment>
<value>1</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\nominalgroups</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1</parent_path_segment>
<value>C_SCOUT</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value1</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value1\ascending</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value1</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value1\index</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value1</parent_path_segment>
<value>0</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value1\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value1</parent_path_segment>
<value>STUDY_INSTANCE_UID</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value1\sort</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value1</parent_path_segment>
<value>STUDY_DATE</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value1\valuetype</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value1</parent_path_segment>
<value>reference</value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value2</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1</parent_path_segment>
<value></value>
</node>

<node>
<path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value2\name</path_segment>
<parent_path_segment>dp_20200708160719_hie006_imp1\nominalgroups\nominalgroup1\value2</parent_path_segment>
<value>IMAGE_TYPE</value>
</node>

<node>